version: '3'

services:
  web:
    container_name: lstm-imdb-flask-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.venv
